### ISSUE TITLE
Tool does not run if it cannot check updates. 

### ISSUE THREAD

**Issue by vload** [lu-cs-sde/codeprober#2]
This means that an internet connection is needed in order to use it.

**Comment by Kevlanche** [comment]
Thanks for the report! I have tried turning off internet and I could not reproduce this issue. Though I suppose certain kinds of connection loss, and certain operating systems/etc could result in network not immediately failing the request (as it does for me), but rather drags it out for a long while.

I changed it so that version checking no longer blocks other requests from running. Hopefully this should also fix your scenario.
